export const FETCH_CAKES_SUCCESS = 'FETCH_CAKES_SUCCESS';
export const FETCH_CAKES_FAILURE = 'FETCH_CAKES_FAILURE';

export const ADD_CAKE_SUCCESS = 'ADD_CAKE_SUCCESS';
export const ADD_CAKE_FAILURE = 'ADD_CAKE_FAILURE';

export const DELETE_CAKE_SUCCESS = 'DELETE_CAKE_SUCCESS';
export const DELETE_CAKE_FAILURE = 'DELETE_CAKE_FAILURE';

export const UPDATE_CAKE_SUCCESS = 'UPDATE_CAKE_SUCCESS';
export const UPDATE_CAKE_FAILURE = 'UPDATE_CAKE_FAILURE';
